"""add upvote module

Revision ID: 1b28b8da547f
Revises: 91916cc19b2b
Create Date: 2019-09-20 08:11:48.295069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b28b8da547f'
down_revision = '91916cc19b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upvotes', 'upvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
